create extension if not exists vector;

create table if not exists public.rag_documents (
  id bigint generated by default as identity primary key,
  source_key text not null,
  source_name text not null,
  source_url text,
  title text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  chunk_index integer not null default 0,
  embedding vector(1024) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_key, chunk_index)
);

create index if not exists rag_documents_embedding_idx
  on public.rag_documents
  using hnsw (embedding vector_cosine_ops);

create index if not exists rag_documents_source_name_idx
  on public.rag_documents (source_name);

create or replace function public.match_documents(
  query_embedding vector(1024),
  match_count integer default 5,
  source_name_filter text default null
)
returns table (
  id bigint,
  source_key text,
  source_name text,
  source_url text,
  title text,
  content text,
  metadata jsonb,
  chunk_index integer,
  similarity double precision
)
language sql
stable
as $$
  select
    rag_documents.id,
    rag_documents.source_key,
    rag_documents.source_name,
    rag_documents.source_url,
    rag_documents.title,
    rag_documents.content,
    rag_documents.metadata,
    rag_documents.chunk_index,
    1 - (rag_documents.embedding <=> query_embedding) as similarity
  from public.rag_documents
  where source_name_filter is null or rag_documents.source_name = source_name_filter
  order by rag_documents.embedding <=> query_embedding
  limit match_count;
$$;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table public.rag_documents to service_role;
grant select on table public.rag_documents to anon, authenticated, service_role;
grant execute on function public.match_documents(vector(1024), integer, text) to anon, authenticated, service_role;